apiVersion: v1
kind: Secret
metadata:
  name: kubefate-secret
  namespace: kube-fate
type: Opaque
stringData:
  kubefateUsername: admin
  kubefatePassword: admin
  mariadbUsername: kubefate
  mariadbPassword: kubefate